# Generated by Django 4.0.3 on 2022-09-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_category_listing_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Title',
            new_name='title',
        ),
    ]
