# Generated by Django 4.0.3 on 2022-09-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='itemDescription',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='itemPrice',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='itemTitle',
            new_name='Title',
        ),
    ]
